# Jenkins Configuration as Code (JCasC) for NSW Stamp Duty Test Pipeline
# This file defines the Jenkins configuration programmatically

jenkins:
  systemMessage: "NSW Stamp Duty Test Pipeline - Automated Testing Environment"
  
  # Global security settings
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "${ADMIN_PASSWORD}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  # Node.js installation
  tools:
    nodejs:
      - name: "NodeJS-20"
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: "20.x"
                    npmPackagesRefreshHours: 24

  # Global properties
  globalProperties:
    - envVars:
        env:
          - key: "NODE_ENV"
            value: "test"
          - key: "CYPRESS_CACHE_FOLDER"
            value: "/tmp/cypress-cache"

# Job configuration
jobs:
  - script: >
      pipelineJob('nsw-stamp-duty-tests') {
        description('Automated testing pipeline for NSW Stamp Duty Calculator')
        
        parameters {
          choiceParam('TEST_TYPE', ['all', 'stamp-duty', 'headed', 'chrome', 'firefox'], 'Type of tests to run')
          booleanParam('CLEAN_ARTIFACTS', true, 'Clean previous test artifacts before running tests')
          booleanParam('GENERATE_REPORTS', true, 'Generate detailed test reports')
        }
        
        triggers {
          // Manual trigger only - no automatic builds
        }
        
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/your-username/NSWStampDuty.git')
                  credentials('github-credentials')
                }
                branch('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
        
        logRotator {
          numToKeep(50)
          daysToKeep(30)
          artifactNumToKeep(10)
          artifactDaysToKeep(7)
        }
      }

# Plugin configurations
plugins:
  - name: "htmlpublisher"
    version: "1.25"
  - name: "junit"
    version: "1.53"
  - name: "mochawesome-reporter"
    version: "1.0.0"
  - name: "cucumber-reports"
    version: "5.7.4"
  - name: "slack"
    version: "2.48"
  - name: "blueocean"
    version: "1.25.3"

# Credentials - Configure manually in Jenkins UI
# Go to Manage Jenkins > Manage Credentials > Add Credentials
# Add GitHub Personal Access Token with ID: github-credentials
